version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node

    steps:
      - checkout

      # Install AWS CLI
      - run:
          name: Install AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install

      # Install dependencies
      - run:
          name: Install Dependencies
          command: npm install

      # Build the project
      - run:
          name: Build
          command: npm run build

      # Deploy to S3
      - run:
          name: Deploy to S3
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region $AWS_DEFAULT_REGION

            aws s3 sync dist s3://homemadeticketsellerbucket --delete
      
      # Invalidate Cloudfront Cache
      -run:
          name: Invalidate Cloudfront Cache
          command: aws cloudfront create-invalidation --distribution-id "E1ZIKN8PYN13UK" --paths "/*"
