version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.16

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Dependencies
          command: yarn install

      # Build the project
      - run:
          name: Build Project
          command: yarn build

      - run:
          name: Deploy to S3
          command: |
            pip install awscli

      # Deploy to S3
  deploy:
    docker:
      - image: innovatorjapan/awscli:latest
    steps:
      - run:
          name: Deploy to S3
          command: |
            pip install awscli --upgrade --user
            export PATH=$PATH:/home/circleci/.local/bin

            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region $AWS_DEFAULT_REGION

            aws s3 sync dist s3://homemadeticketsellerbucket --delete
