version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Dependencies
          command: npm install

      # Build the project
      - run:
          name: Build Project
          command: npm run build

      # Install pip
      - run:
          name: Install pip3
          command: sudo apt install python3-pip

  deploy:
    docker:
      - image: innovatorjapan/awscli:latest
    steps:
      - run:
          name: Deploy to S3
          command: |
            export PATH=$PATH:/home/circleci/.local/bin

            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region $AWS_DEFAULT_REGION

            aws s3 sync dist s3://homemadeticketsellerbucket --delete

workflows:
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master 
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master 